### PR TITLE
[#1793] Fix +1 links corner case

### PR DESCRIPTION
**Pull request by kardan**
We exclude Project.reporting_org() org from the partners list to
get counting & display correct. The problem was that a project could
have a reporting org and then a partner that was another org.

### CODE REVIEW

**Comment by kardan** [comment]
Testplan:
Case 1:
When a project only have one partner.
Then no + more link should on the project main page

Case 2:
When a project have one reporting org and another partner.
Then the reporting org  + more link with the partner should on the project main page

Case 3:
When a project have one reporting org and the same as partner.
Then the reporting org & no + more link on project main page should be visible

**Comment by KasperBrandt** [comment]
It works on the project main page, but not yet on the project listing page (that wasn't in the issue either..). Can you take a look at that part as well :)?

**Comment by kardan** [comment]
Good point, I'll have a look!

**Comment by kardan** [comment]
@KasperBrandt  Finally managed to get tooltips working in the project directory. Not sure why but I didn't spot the "data-container" & "data-class” attributes on https://github.com/akvo/akvo-rsr/commit/6481d993c1fb586ae4c9f65d43b73f3f0563f7cc#diff-a0683d374328efb31d45e88380829bcdL17 which for some reason blocked the tooltip to appear in the project list but not on the project main page.

**Pull request merged**
