### PR TITLE
[Fixes #1750] Fix project funding template

### LINKED ISSUE #1750: Partnerships with no organisations should not be allowed
## Test plan
GIVEN the project editor
WHEN the project has a funding partnership without an organisation
THEN an error should be displayed that the organisation field isn't filled in

### PR DESCRIPTION
**Pull request by KasperBrandt**
Fixes #1750

### CODE REVIEW

**Comment by zzgvh** [comment]
See comment on #1750

**Comment by KasperBrandt** [comment]
@zzgvh Updated it now, but also with the IATI partner types branch (because of migrations). Anyhow, the Partnership.organisation field is now mandatory.

**Comment by zzgvh** [comment]
I can still save a partnership with only a type:

sceenshot

and I'm not sure there's any point allowing that?

**Comment by KasperBrandt** [comment]
Ah, it doesn't always work indeed :(.. Looking into it now.

**Pull request merged**
