### PR TITLE
[#4026] EUTF organisation results and indicators excel report.

### LINKED ISSUE #4026: EUTF Organisation Results and Indicators Export excel report

### PR DESCRIPTION
**Pull request by zuhdil**
- [ ] Test plan | Unit test | Integration test
- [ ] Documentation

Closes #4026

### CODE REVIEW

**Comment by punchagan** [comment]
This looks good but the report takes about 2 minutes to get generated on my machine, locally. Did you do any profiling on this to see if we can make things faster? Or do we have to live with this? :thinking:

**Comment by punchagan** [comment]
I have some time to look into this. I will do that.

**Comment by punchagan** [comment]
@zuhdil I pushed a change for this. Can you tell me if this speeds up things for you, and if the change looks good? Thanks!

**Comment by zuhdil** [comment]
@punchagan , I'm trying to optimise the performance, can you check if my changes do improve the performance on your machine? Thanks!

**Comment by punchagan** [comment]
This is better than what we had before, and I think we can merge it for now. If and when we have more time, we could look at seeing if we can improve this further.

**Pull request merged**
