### PR TITLE
[#1032 #1073] Added sectors as filter on project directory page

### PR DESCRIPTION
**Pull request by KasperBrandt**
- Added sectors as filter on project directory page
- Cleanup sectors with data migration
  - No double values (projects linked to same sector multiple times)
  - Both sectors and categories (e.g. when linked to 11123, also link to category 111)
  - Set correct vocabulary (DAC for 5 digit code and DAC-3 for 3 digit code)
- Only show 'reset all filters' when filters in place (issue #1073)

### CODE REVIEW

**Comment by iperdomo** [comment]
## Checklist

* [ ] Test plan
* [ ] Copyright header
* [ ] Code formatting

**Comment by KasperBrandt** [comment]
Superseded by #1089.

**Comment by kardan** [comment]
@KasperBrandt can we kill https://github.com/akvo/akvo-rsr/tree/1032_sector_filters?

**Comment by KasperBrandt** [comment]
Yes :)

**Pull request closed without merging**
