### PR TITLE
Flag to remove REQUIRED_AUTH_GROUPS

### LINKED ISSUE #3630: Backend not starting with empty DB
The logic to create the REQUIRED_AUTH_GROUPS is run before any migrations, hence it fails 
to execute when RSR backend runs against an empty database.

### PR DESCRIPTION
**Pull request by dlebrero**
Set when running migrations.

Fixes #3630

### CODE REVIEW

**Comment by punchagan** [comment]
Is there a commit where I can reproduce the problem? on the training env branch? 

I think we should look to move [this code](https://github.com/akvo/akvo-rsr/blob/master/akvo/urls.py#L238) out of `urls.py` - this isn't a standard Django practice, and I've left it there since it seemed to cause no problems until now. 

Perhaps, it can be moved to `models/__init__.py`.

**Comment by dlebrero** [comment]
I think you can reproduce it by commenting out https://github.com/akvo/akvo-rsr/blob/fe5324e1a059fa7e792993784eca0eb04916d8e6/postgres/setup.sh#L18-L17 and doing a docker-compose down && up

I can move the code there and test. Are you concern about dependencies between the model and the utils?

**Comment by punchagan** [comment]
> I think you can reproduce it by commenting out https://github.com/akvo/akvo-rsr/blob/fe5324e1a059fa7e792993784eca0eb04916d8e6/postgres/setup.sh#L18-L17 and doing a docker-compose down && up

I tried that but there the postgres `init.sql`fails. 

> I can move the code there and test. Are you concern about dependencies between the model and the utils?

If you could test that, that would be nice. I'm not too concerned about the dependency

**Comment by dlebrero** [comment]
> > I think you can reproduce it by commenting out https://github.com/akvo/akvo-rsr/blob/fe5324e1a059fa7e792993784eca0eb04916d8e6/postgres/setup.sh#L18-L17 and doing a docker-compose down && up
> 
> I tried that but there the postgres `init.sql`fails.

You have to also remove that `init.sql` line and the wait-for-deps at https://github.com/akvo/akvo-rsr/blob/7c3e47ef134ae8440005232c648c99afe3423f8a/scripts/docker/dev/start-django.sh#L12. As we do not wait for Postgres to be ready, the `web` container will fail to start, just wait a bit for the DB to be up and running and then start the `web` container again.
 
> 
> > I can move the code there and test. Are you concern about dependencies between the model and the utils?
> 
> If you could test that, that would be nice. I'm not too concerned about the dependency

Still the same issue if I move 
   
     if settings.REQUIRED_AUTH_GROUPS:
         check_auth_groups(settings.REQUIRED_AUTH_GROUPS)

to the bottom of the `__init.py` file.

```
web_1          | Traceback (most recent call last):
web_1          |   File "manage.py", line 27, in <module>
web_1          |     execute_from_command_line(sys.argv)
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
web_1          |     utility.execute()
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute
web_1          |     django.setup()
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
web_1          |     apps.populate(settings.INSTALLED_APPS)
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
web_1          |     app_config.import_models()
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
web_1          |     self.models_module = import_module(models_module_name)
web_1          |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
web_1          |     __import__(name)
web_1          |   File "/var/akvo/rsr/code/akvo/rsr/models/__init__.py", line 501, in <module>
web_1          |     check_auth_groups(settings.REQUIRED_AUTH_GROUPS)
web_1          |   File "/var/akvo/rsr/code/akvo/utils.py", line 370, in check_auth_groups
web_1          |     Group.objects.get_or_create(name=group_name)
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
web_1          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 464, in get_or_create
web_1          |     return self.get(**lookup), False
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 374, in get
web_1          |     num = len(clone)
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 232, in __len__
web_1          |     self._fetch_all()
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1121, in _fetch_all
web_1          |     self._result_cache = list(self._iterable_class(self))
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 53, in __iter__
web_1          |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
web_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
web_1          |     raise original_exception
web_1          | django.db.utils.ProgrammingError: relation "auth_group" does not exist
web_1          | LINE 1: ...ELECT "auth_group"."id", "auth_group"."name" FROM "auth_grou...
```

**Comment by punchagan** [comment]
How about just changing the utility function that checks for the presence of these groups? 

```diff
 def check_auth_groups(group_names):
     for group_name in group_names:
-        Group.objects.get_or_create(name=group_name)
+        try:
+            Group.objects.get_or_create(name=group_name)
+        except ProgrammingError:
+            pass
```

**Comment by dlebrero** [comment]
I would rather be explicit. From the code, it is not obvious why we would be ignoring those errors.

**Comment by punchagan** [comment]
Fair point! I'll merge your PR.

**Pull request merged**
