### PR TITLE
[#3534] Fix map not appearing

### PR DESCRIPTION
**Pull request by zuhdil**
- [ ] Test plan | Unit test | Integration test
- [ ] Copyright header
- [ ] Code formatting
- [ ] Documentation
- [ ] Change log entry

### CODE REVIEW

**Comment by punchagan** [comment]
Good catch! Looks good to me. Do you think we need to fix the `ProjectUpdateDirectorySerializer` too?

**Comment by zuhdil** [comment]
I'm not sure, the UI is a bit different with the project directory. So, I think we keep the update directory as it is now and create a separate issue if we found a problem with it later.

**Comment by punchagan** [comment]
What exactly do you mean, when you say the UI is a bit different? The Project directory and project update directory seem to be trying to re-using as much code as possible.

**Comment by punchagan** [comment]
Merging based on @zuhdil explanation that it is missing fields that are causing a problem here, not incorrect values in the DB.  The `ProjectUpdateDirectorySerializer` is already doing the right thing.

**Pull request merged**
