### PR TITLE
Closes #4536 Redesign Enumerator View

### LINKED ISSUE #4536: Redesign Enumerator view
## Summary
Redesign enumerator view such as :

1. Show submit button when period open collapse (expanded).
2. Change the size of the point indicator to be smaller.
3. Add border color based on indicator submission status (eg: red border to reject) like the mockup below.

## Mockup
[https://xd.adobe.com/view/d86e20e2-fff3-4c80-9c6e-411ee6e7b900-8d3d/screen/6683455d-a606-47b3-bfc0-2da4854d1a02](https://xd.adobe.com/view/d86e20e2-fff3-4c80-9c6e-411ee6e7b900-8d3d/screen/6683455d-a606-47b3-bfc0-2da4854d1a02)

### PR DESCRIPTION
**Pull request by ifirmawan**
1. Replace checklist icon with small circle
2. Modify enumerator scss to create small circle.
3. Small circle color update based on its status.
4. Remove loading indicator at the left side submit button.
5. Create the approve all buttons sticky and change lock button type is filled danger.

- [ ] Test plan | Unit test | Integration test
- [ ] Documentation

### CODE REVIEW

**Comment by loicsans** [comment]
First comments: 
Screenshot 2021-06-11 at 13 58 26
In the results admin tab: 
1. remove the "Unlock" and "lock" buttons, they should only appear in the Results overview tab
2. Unbold the tab title "To be reported" when tab is selected, to avoid the jump on tab switching (Same for "Pending approval when se;=lected")
3. when "Pending approval" is selected and empty the text: "You have no updates pending approval", should be styled exactly like the text that says "No submission due"on the to be reported tab.

**Comment by loicsans** [comment]
The results overview tab:
Screenshot 2021-06-11 at 14 01 49
As per the visuals I had made: We should increase the spacing between each results and by default, they should be opened (showing the indicators), as shown here:
Screenshot 2021-06-11 at 14 03 14

**Comment by ifirmawan** [comment]
Thank you @loicsans , I will update based on this feedback on PR #4555

**Comment by loicsans** [comment]
Screenshot 2021-06-15 at 12 35 35
Remove the "Approve all" / "Decline all"CTA's at the bottom

**Pull request merged**
