### PR TITLE
Add flake8 checks

### LINKED ISSUE #2477: Replace Landscape code quality tests with flake8 and/or pylint
Landscape doesn't seem to always run, and sometimes just hangs on some pull-requests without any reason.  It might be easier to just run our own linting/checking tool on Travis.

### PR DESCRIPTION
**Pull request by punchagan**
- The checks will run automatically on Travis.
- Getting a 100% coverage will require significantly more effort and
  work, but having flake8 checks can give us some of the benefits for a
  relatively low cost.  Issues like #2361 can easily be avoided.
# Test plan
- All the tests should pass (but our coverage isn't all the way there)
- Some basic manual testing?

This is a fairly big change, but most of the changes were made automatically using `autopep8` and `autoflake`.  Each commit tries to stick to one kind of fix, to help review. 

Closes #2477

### CODE REVIEW

**Comment by punchagan** [comment]
> I like this in general. I'm using PyCharm so I get some of PEP8 for free, but definitely not all.

Sure. I have some checks in my editor too, and that's how I found #2361. But, I think it is good to have some checks before merging/deploying to avoid trivial bugs. 

> One personal issue is that I don't like the 79 char line length limit , I prefer 100 chars. Sure I can adjust, but there's a lot of code that's up to 100 chars wide...

I am not very fond of this limit either. I've actually disabled this check, when running it on travis (E501). Sorry for not mentioning this in the PR description. 

> For some reason Travis isn't happy running this right now.

There was a missing import which was fixed in #2361 and Travis is now happy.

**Comment by zzgvh** [comment]
Great! So how do we merge this? Ideally we shouldn't have any other outstanding PRs when this is merged as there's a good chance these changes will introduce conflicts.

**Comment by punchagan** [comment]
All the pending PRs are small, except for the DRF update PR.  We can either wait for them to be merged, or just go ahead with merging this one, because the conflicts will be pretty small, if any. 

For the DRF update PR: If you think that would be merged in reasonably soon, this can wait for that PR to be in. Otherwise, I can help rebase that PR onto the new develop branch, after this has been merged.

**Comment by zzgvh** [comment]
Yep, you're right. We might as well merge this then. 

I have researched one of the larger fixes needed in the DRF update branch, it's the endpoint pagination. What's needed there is mostly code removal and some config since DRF 3 includes much better pagination tools, so the custom hack Kasper wrote after the DRF update branch was made can be thrown away in large part. 

So if you think you can fix the style related changes in that branch it'd be great and shouldn't make things harder on my end.

**Comment by punchagan** [comment]
Let's merge it then! :+1: 

> So if you think you can fix the style related changes in that branch it'd be great and shouldn't make things harder on my end.

I can help with this, once that branch is ready for a review.  Or whenever you think, this should be done.

**Comment by punchagan** [comment]
Commits need reference to an issue number

**Comment by punchagan** [comment]
This should now be merge-able, @zzgvh. (after #2476 is merged)

**Pull request merged**
