### PR TITLE
[#4507] Bug fixing initial indicator description

### PR DESCRIPTION
**Pull request by ifirmawan**
Description doesn't match with the first title.
* create initial states for indicators.
* change condition of preview url params.
* setSelected indicator after filtering periods isPeriodNeedsReporting.

- [ ] Test plan | Unit test | Integration test
- [ ] Documentation

### CODE REVIEW

**Comment by punchagan** [comment]
@ifirmawan if you are working on a branch, it is nice to squash commits into single logical ones, wherever possible. I think the 3 commits here can be squashed into a single one, so that the commit history makes more sense to anyone looking at it in future.

**Comment by ifirmawan** [comment]
noted @punchagan , I will do that in the future

**Comment by punchagan** [comment]
You can do that with the current PR too. Rebase against the `master` and squash the commits into a single one.

**Comment by ifirmawan** [comment]
I see, I'm trying @punchagan.

**Review by zuhdil — APPROVED** [review]

**Pull request merged**
