### PR TITLE
Make project directory loading and filtering more dynamic

### PR DESCRIPTION
**Pull request by punchagan**
- [ ] Test plan | Unit test | Integration test
- [ ] Copyright header
- [ ] Code formatting
- [ ] Documentation
- [ ] Change log entry

### CODE REVIEW

**Comment by punchagan** [comment]
- [ ] Think about how this effects SEO
- [ ] There are some tests for API responses on partner sites. Check if the UI works fine too.

**Comment by zzgvh** [comment]
I found a bug. 

Go to an organisation page via the link for main partner in a project. On the org page select one of the links back to the project listing page under the Projects in RSR heading, e.g. IMPLEMENTATION.

Now in some cases, it's a little hard to provoke, when you click the reset filter link, all selects get populated with undefined objects. I can provoke it most of the time if I open one of the other selects and then click reset.

screenshot_258

**Comment by zzgvh** [comment]
Layout problem:

screenshot_259

I've seen this on test too where there are actual photos so it's not because I don't have pics locally.

**Comment by zzgvh** [comment]
I think there's a need for some feedback when the search is executed. On a slow machine, like my local, it takes quite a while before the filter kicks in and there is no visual indication that something about to happen.

**Comment by punchagan** [comment]
> I think there's a need for some feedback when the filtering is executed. On a slow machine, like my local, it takes quite a while before the filter kicks in and the only visual indication that something might be happening is that the selects get grayed out.

I've added a spinner for this

image

**Comment by punchagan** [comment]
> I've seen this on test too where there are actual photos so it's not because I don't have pics locally.

Yes, I have seen this too.  I'll take a stab at this, but it's best if @loicsans looks at it.

**Comment by punchagan** [comment]
Closing in favor of #3197

**Pull request closed without merging**
