### PR TITLE
[#3814] s5 jump to results & indicators

### PR DESCRIPTION
**Pull request by martinchristov**
- [ ] Test plan | Unit test | Integration test
- [ ] Documentation

### CODE REVIEW

**Comment by martinchristov** [comment]
1. What text/icon should the button have? Currently it's "Open" not sure if this is best.
2. There is a slight delay after clicking the button to give time to the modal to close & accordion to switch before scroll is performed. Do you feel it's too much the delay?

**Comment by punchagan** [comment]
> There is a slight delay after clicking the button to give time to the modal to close & accordion to switch before scroll is performed. Do you feel it's too much the delay?

The first time it seemed like a little too long. But, after I used it once, it didn't feel like too long.

**Comment by punchagan** [comment]
> What text/icon should the button have? Currently it's "Open" not sure if this is best.

Should it be a separate button? Or could the titles themselves be clickable?

**Comment by punchagan** [comment]
We should probably move this discussion to Zulip to get inputs from Anthony, as well, I guess.

**Comment by martinchristov** [comment]
We'll have to merge to develop for Anthony to see it.
As for titles being clickable - they already are clickable but to expand-collapse. I think it should remain as so and the "jump to" as a separate button as it is not the primary action.

**Comment by punchagan** [comment]
> What text/icon should the button have? Currently it's "Open" not sure if this is best.

We could use the word `Edit` instead of `Open`.  Open could also refer to opening the folded accordion.

**Pull request merged**
