### PR TITLE
[#4179] Use default_storage to create IATI xml files

### PR DESCRIPTION
**Pull request by punchagan**
- [ ] Test plan | Unit test | Integration test
- [ ] Documentation

### CODE REVIEW

**Comment by punchagan** [comment]
Yes, as part of the cron job.

**Comment by punchagan** [comment]
`./manage.py iati_export` to trigger it manually.

**Comment by dlebrero** [comment]
In the [console](https://console.cloud.google.com/logs/viewer?project=akvo-lumen&minLogLevel=0&expandAll=false&timestamp=2020-05-13T08:11:26.448000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-05-13T07:11:57.096Z&dateRangeEnd=2020-05-13T08:11:57.096Z&interval=PT1H&resource=k8s_container%2Fcluster_name%2Fproduction%2Fnamespace_name%2Fdefault%2Fcontainer_name%2Frsr-backend&scrollTimestamp=2020-05-13T08:11:04.074856122Z&filters=text:iati_import), I see that the cron jobs do not pick up the correct log level (I expect the log level to be the same as the gunicorn one, that is INFO). 

This makes me wonder if the cronjobs will read the correct config regarding the google storage or not.

**Comment by punchagan** [comment]
Ah, interesting. I'll investigate. :)

**Comment by dlebrero** [comment]
Does https://github.com/akvo/akvo-rsr/blob/1b553b76f15ad72c7b27552def00ebf16f6e9d3d/akvo/iati/exports/iati_org_export.py#L35 need fixing also?

**Comment by punchagan** [comment]
Ah, yes. I did a search for mediaroot, but somehow overlooked this. Thanks for the catch!

**Comment by punchagan** [comment]
> In the [console](https://console.cloud.google.com/logs/viewer?project=akvo-lumen&minLogLevel=0&expandAll=false&timestamp=2020-05-13T08:11:26.448000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-05-13T07:11:57.096Z&dateRangeEnd=2020-05-13T08:11:57.096Z&interval=PT1H&resource=k8s_container%2Fcluster_name%2Fproduction%2Fnamespace_name%2Fdefault%2Fcontainer_name%2Frsr-backend&scrollTimestamp=2020-05-13T08:11:04.074856122Z&filters=text:iati_import), I see that the cron jobs do not pick up the correct log level (I expect the log level to be the same as the gunicorn one, that is INFO).

I think it should. We write the env vars to `/etc/environment`. Our [Django settings](https://github.com/akvo/akvo-rsr/blob/develop/akvo/settings/90-finish.conf#L95-L99) have a debug level set to `DEBUG` by default, and the gunicorn debug level is set as `GUNICORN_DEBUG_ARGS`. This environment variable wouldn't be read by the cron jobs, and that's why the cron jobs seem to use the `DEBUG` level instead of `INFO`.

**Comment by punchagan** [comment]
> This makes me wonder if the cronjobs will read the correct config regarding the google storage or not.

It should be easy to test this on the test server. :)

**Comment by dlebrero** [comment]
Merging so you can test in the test server

**Comment by dlebrero** [comment]
By the way, it would be great to fix the debug level. It annoys me when looking at the RSR logs :P

**Comment by punchagan** [comment]
> Merging so you can test in the test server

That seems to work. :)

> By the way, it would be great to fix the debug level. It annoys me when looking at the RSR logs :P

Yes, I'll send a patch to fix that, separately.

**Pull request merged**
