### PR TITLE
[#1025] Added document upload

### PR DESCRIPTION
**Pull request by KasperBrandt**
First #1048 will have to be merged in, as it is merged in this branch as well (because of migrations).

### CODE REVIEW

**Comment by iperdomo** [comment]
## Checklist

* [ ] Test plan
* [ ] Copyright header
* [ ] Code formatting

**Comment by KasperBrandt** [comment]
Superseded by #1089.

**Comment by kardan** [comment]
@KasperBrandt can we delete the https://github.com/akvo/akvo-rsr/tree/1025_document_upload branch?

**Comment by KasperBrandt** [comment]
Yes :)

**Pull request closed without merging**
