### PR TITLE
#1624 piwik

### PR DESCRIPTION
**Pull request by kardan**

### CODE REVIEW

**Comment by kardan** [comment]
Testplan:
In the admin on the gooddeeds.localakvoapp.org RSR page add 30 to the Piwikid field.
Since the feature uses the current url and we only got live data in Piwik we need to do some commenting :-(

Comment:
https://github.com/akvo/akvo-rsr/blob/%231624-piwik/akvo/rsr/static/scripts-src/piwik-reporting.js#L84
https://github.com/akvo/akvo-rsr/blob/%231624-piwik/akvo/rsr/static/scripts-src/piwik-reporting.js#L85

Uncomment:
https://github.com/akvo/akvo-rsr/blob/%231624-piwik/akvo/rsr/static/scripts-src/piwik-reporting.js#L88
https://github.com/akvo/akvo-rsr/blob/%231624-piwik/akvo/rsr/static/scripts-src/piwik-reporting.js#L89

Now a "hits: <n>" should be visible in the footer.

To disable the feature add the "PIWIK_DISABLE_HITS = True" setting.

**Comment by kardan** [comment]
Btw, just realised that the UI part of this work is just me who did "something". It can easily be changed in https://github.com/akvo/akvo-rsr/blob/%231624-piwik/akvo/rsr/static/scripts-src/piwik-reporting.js#L13

**Comment by KasperBrandt** [comment]
@gabemart Do you have time to look at the UI maybe? Today or Monday? Currently, the counter is in the project footer:

screen shot 2015-07-10 at 09 46 32

**Comment by kardan** [comment]
@lauraroverts you seemed hesitant when we talked about this, not sure if this been decided or not.

**Comment by gabemart** [comment]
@KasperBrandt I've replaced inline styles with SASS and I changed a couple of selector names, but other than that I think Daniel's styling is good

**Pull request merged**
