### PR TITLE
[#5143] Create cumulative updates hint in enum web form

### PR DESCRIPTION
**Pull request by ifirmawan**
# TODO / Done

Summarize what has been changed / what has to be done in order to finalize the PR.

 - [x] Modify PrevUpdate a reusable component to handle previous updates and cumulative updates.
 - [x] Code cleaning by replacing hard-coded measure value with constant variable ```measureType``` in app/utils/constants.js

# Test plan

What tests are necessary to ensure this works or doesn't break anything working

 - [ ] Login as an Enumerator and submit an update on the reporting period

### CODE REVIEW

**Comment by zuhdil** [comment]
The component should not display `null` values
Screenshot_2022-10-26T06:07:24 165336747

**Review by zuhdil — COMMENTED** [review]
The component should not display `null` values

Screenshot_2022-10-26T06:07:24 165336747

**Comment by ifirmawan** [comment]
noted, I'm working on it

**Comment by ifirmawan** [comment]
> The component should not display `null` values
> 
> Screenshot_2022-10-26T06:07:24 165336747

noted, I'm working on it

**Review by zuhdil — APPROVED** [review]

**Pull request merged**
