### PR TITLE
[#2456]Sort results and indicators on order, id

### PR DESCRIPTION
**Pull request by stellanl**
- [X] Test plan | Unit test | Integration test
- [ ] Copyright header
- [ ] Code formatting
- [ ] Documentation
- [ ] Change log entry

### CODE REVIEW

**Comment by punchagan** [comment]
@stellanl Looks like this hasn't been deployed on the test report server. Can you do that, so that I may test and merge this PR? Thanks!

**Comment by stellanl** [comment]
It got lost when the database was restored from live. Redeploying it.

**Comment by punchagan** [comment]
That's what I thought. Thanks!

**Comment by stellanl** [comment]
Deployed.

**Comment by punchagan** [comment]
Checked on test server and looks good to me.

**Comment by punchagan** [comment]
Closes #2456

**Pull request merged**
